/* ═══════════════════════════════════════════════════════
   Nodo — Type Definitions
   ═══════════════════════════════════════════════════════ */

export type Language = "es" | "en";

export interface NavItem {
  label: string;
  href: string;
}

export interface Service {
  id: string;
  icon: string;
  title: string;
  description: string;
  deliverables: string[];
  techStack: string[];
}

/* Bilingual string — used inline in projects.ts so case studies stay in one file */
export type Bilingual = { es: string; en: string };

export type ProjectCategory =
  | "dev"
  | "wordpress"
  | "ia"
  | "ecommerce"
  | "uiux"
  | "maintenance";

export type ProjectRole = "lead" | "support" | "design-only" | "maintenance";
export type ProjectVisibility = "public" | "nda" | "anonymized";
export type ProjectAccent = "blue" | "cyan" | "purple" | "indigo";

export interface ProjectMetric {
  /** Numeric value, animatable from 0 with count-up. */
  value: number;
  prefix?: string;
  suffix?: string;
  label: Bilingual;
}

export interface ProjectScreenshot {
  /** Path under /public/projects/[slug]/ — or null while we use placeholders. */
  src: string | null;
  alt: Bilingual;
  /** Short caption shown under the image in the gallery. Falls back to alt. */
  caption?: Bilingual;
  aspect: "16:9" | "16:10" | "4:3" | "9:16" | "1:1";
  frame?: "browser" | "phone" | "raw";
  hero?: boolean;
  /** Optional second image rendered side-by-side in the same slide.
   *  Useful for paired mobile screens (e.g. home + product detail). */
  pair?: { src: string; alt: Bilingual };
  /** Optional download/preview link rendered as a button under the caption.
   *  Use for downloadable artifacts produced by the feature shown — e.g.
   *  the actual PDF generated by a quote tool, a sample report, etc. */
  link?: { url: string; label: Bilingual };
}

export interface ProjectTimelineStep {
  title: Bilingual;
  body: Bilingual;
}

export interface Project {
  /** kebab-case URL slug */
  slug: string;
  /** Lower number = earlier in the grid. */
  order: number;
  /** Featured project shown above the grid. Only one at a time typically. */
  featured?: boolean;
  /** Toggle without deleting. */
  published: boolean;

  /* META */
  category: ProjectCategory;
  year: number;
  duration: Bilingual;
  industry: Bilingual;

  /* CLIENT */
  client: {
    name: string;
    visibility: ProjectVisibility;
    /** Optional client logo path. */
    logo?: string;
    /** Optional live URL. */
    liveUrl?: string;
  };

  /* NODO ROLE */
  role: ProjectRole;
  team: Bilingual;

  /* COPY */
  title: string;
  tagline: Bilingual;
  summary: Bilingual;

  /* CASE STUDY (optional — light projects can skip this) */
  caseStudy?: {
    problem: Bilingual;
    approach: ProjectTimelineStep[];
    outcome: Bilingual;
    quote?: {
      text: Bilingual;
      author: string;
      role: Bilingual;
    };
  };

  /* ASSETS */
  thumbnail: ProjectScreenshot;
  screenshots: ProjectScreenshot[];

  /* STACK */
  stack: string[];

  /* METRICS — 0 to 4 entries. */
  metrics: ProjectMetric[];

  /* Brand accent for card / hero glow */
  accent: ProjectAccent;

  /** Optional public repos (back, front, etc.) shown as GitHub buttons
   *  in the case study hero. Only include when the client agrees. */
  repos?: Array<{ label: string; url: string }>;
}

export interface Testimonial {
  id: string;
  quote: string;
  author: string;
  company: string;
  role: string;
}

export interface TeamMember {
  id: string;
  name: string;
  role: string;
  bio: string;
  image: string;
  skills: string[];
  links: {
    linkedin?: string;
    github?: string;
    twitter?: string;
  };
}

export interface ContactFormData {
  name: string;
  email: string;
  serviceType: string;
  budget: string;
  message: string;
}
